

spring:
  datasource:
    url: jdbc:h2:mem:crypto-trading-db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:/db/migration/schema.sql,classpath:/db/migration/import.sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: false
      path: /h2-console

scheduler:
  fixed-rate: 10000

kafka:
  bootstrap-servers: localhost:9092,localhost:9094
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    acks: all
    retries: 3
    batch-size: 16384
    linger-ms: 100
    compression-type: lz4
    max-in-flight-requests-per-connection: 5
    enable-idempotence: true
    retry-backoff-ms: 1000
  topics-source: inbound-symbol-source

logging:
  level:
    root: info
    org.trading.application.*: INFO

source:
  binance:
    url: https://api.binance.com/api/v3/ticker/bookTicker
  huobi:
    url: https://api.huobi.pro/market/tickers
server:
  port: 11080

  servlet:
    context-path: /api